version: '3'
services:
  app:
    container_name: AppHotWheels
    build: .
    ports:
      - '3000:3000'
      - '5000:5000'
    networks:
      - mi-red
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    container_name: mysql-db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: AutoFormulario
    volumes:
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
    ports:
      - '3307:3306'
    networks:
      mi-red:
        aliases:
          - mysql 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 5
networks:
  mi-red: